name: Remove old artifacts

on: workflow_dispatch

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove all artifacts
      uses: actions/github-script@v5
      with:
        script: |
          const { owner, repo } = context.repo;

          const artifacts = await github.rest.actions.listArtifactsForRepo({
            owner,
            repo
          });

          for (const artifact of artifacts.data.artifacts) {
            await github.rest.actions.deleteArtifact({
              owner,
              repo,
              artifact_id: artifact.id
            });
            console.log(`Deleted artifact: ${artifact.name}`);
          }
